name: Publish

on:
  push:
    tags:
      - "*"

  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/tags/') }}

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - {
              target: x86_64,
              interpreter: "3.10 3.11 3.12 3.13 3.14 3.14t 3.15 3.15t pypy3.11",
            }
          - {
              target: x86,
              interpreter: "3.10 3.11 3.12 3.13 3.14 3.14t 3.15 3.15t pypy3.11",
            }
          - {
              target: aarch64,
              interpreter: "3.10 3.11 3.12 3.13 3.14 3.14t 3.15 3.15t pypy3.11",
            }
          - {
              target: armv7,
              interpreter: "3.10 3.11 3.12 3.13 3.14 3.14t 3.15 3.15t pypy3.11",
            }
          - {
              target: s390x,
              interpreter: "3.10 3.11 3.12 3.13 3.14 3.14t 3.15 3.15t pypy3.11",
            }
          - {
              target: ppc64le,
              interpreter: "3.10 3.11 3.12 3.13 3.14 3.14t 3.15 3.15t pypy3.11",
            }

    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false

      - uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.x"

      - uses: PyO3/maturin-action@v1.51.0
        with:
          target: ${{ matrix.platform.target }}
          args: --release --out dist --interpreter ${{ matrix.platform.interpreter }}
          sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
          manylinux: auto
          rust-toolchain: nightly

      - uses: actions/upload-artifact@v7.0.1
        with:
          name: wheels-linux-${{ matrix.platform.target }}
          path: dist

  build-musllinux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - {
              target: x86_64,
              interpreter: "3.10 3.11 3.12 3.13 3.14 3.14t 3.15 3.15t pypy3.11",
            }
          - {
              target: x86,
              interpreter: "3.10 3.11 3.12 3.13 3.14 3.14t 3.15 3.15t pypy3.11",
            }
          - {
              target: aarch64,
              interpreter: "3.10 3.11 3.12 3.13 3.14 3.14t 3.15 3.15t pypy3.11",
            }
          - {
              target: armv7,
              interpreter: "3.10 3.11 3.12 3.13 3.14 3.14t 3.15 3.15t pypy3.11",
            }

    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false

      - uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.x"

      - uses: PyO3/maturin-action@v1.51.0
        with:
          target: ${{ matrix.platform.target }}
          args: --release --out dist --interpreter ${{ matrix.platform.interpreter }}
          sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
          manylinux: musllinux_1_2
          rust-toolchain: nightly

      - uses: actions/upload-artifact@v7.0.1
        with:
          name: wheels-musllinux-${{ matrix.platform.target }}
          path: dist

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        platform:
          - {
              target: x64,
              interpreter: "3.10 3.11 3.12 3.13 3.14 3.14t 3.15 3.15t pypy3.11",
            }
          - { target: x86, interpreter: "3.10 3.11 3.12 3.13 3.14 3.14t 3.15 3.15t" }

    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false

      - uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.x"
          architecture: ${{ matrix.platform.target }}

      - uses: PyO3/maturin-action@v1.51.0
        with:
          target: ${{ matrix.platform.target }}
          args: --release --out dist --interpreter ${{ matrix.platform.interpreter }}
          sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
          rust-toolchain: nightly

      - uses: actions/upload-artifact@v7.0.1
        with:
          name: wheels-windows-${{ matrix.platform.target }}
          path: dist

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        platform:
          - {
              target: x86_64,
              interpreter: "3.10 3.11 3.12 3.13 3.14 3.14t 3.15 3.15t pypy3.11",
            }
          - {
              target: aarch64,
              interpreter: "3.10 3.11 3.12 3.13 3.14 3.14t 3.15 3.15t pypy3.11",
            }

    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false

      - uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.x"

      - uses: PyO3/maturin-action@v1.51.0
        with:
          target: ${{ matrix.platform.target }}
          args: --release --out dist --interpreter ${{ matrix.platform.interpreter }}
          sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
          rust-toolchain: nightly

      - uses: actions/upload-artifact@v7.0.1
        with:
          name: wheels-macos-${{ matrix.platform.target }}
          path: dist

  build-sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false

      - name: Build sdist
        uses: PyO3/maturin-action@v1.51.0
        with:
          command: sdist
          args: --out dist
          rust-toolchain: nightly

      - name: Upload sdist
        uses: actions/upload-artifact@v7.0.1
        with:
          name: wheels-sdist
          path: dist

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    needs:
      - build-linux
      - build-musllinux
      - build-windows
      - build-macos
      - build-sdist

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/download-artifact@v8.0.1
        with:
          pattern: wheels-*
          merge-multiple: true
          path: dist

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
