name: Python Test

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1

jobs:
  test-python:
    if: >-
      contains(github.event.head_commit.message, '!test') ||
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'pull_request'

    name: test ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ endsWith(matrix.python-version, 't') }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.13t"
          - "3.14"
          - "3.14t"
          - "pypy3.11"

    steps:
      - uses: actions/checkout@v6.0.2

      - uses: dtolnay/rust-toolchain@nightly

      - uses: actions/setup-python@v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - run: pip install virtualenv pytest pytest-asyncio hypothesis maturin
      - run: virtualenv --no-vcs-ignore .venv
      - run: maturin develop --features small-offset
      - run: pytest -v
        env:
          HYPOTHESIS_PROFILE: slow

  test-os:
    if: >-
      contains(github.event.head_commit.message, '!test') ||
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'pull_request'

    name: test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]

    steps:
      - uses: actions/checkout@v6.0.2

      - uses: dtolnay/rust-toolchain@nightly

      - uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.13"
          allow-prereleases: true

      - run: pip install virtualenv pytest pytest-asyncio hypothesis maturin
      - run: virtualenv --no-vcs-ignore .venv
      - run: maturin develop --features small-offset
      - run: pytest -v
        env:
          HYPOTHESIS_PROFILE: slow
